# -*- coding: utf-8 -*-
"""Problemas solucionados - general

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhI-cn6SCyVOsVV1qY51O0eHthdzzz0N
"""

#Install libraries
!pip install pulp -q

"""# Problema de Optimización: Producción de Muebles

Una fábrica produce dos tipos de muebles: **sillas** y **mesas**.

- Cada silla genera una utilidad de **30**.
- Cada mesa genera una utilidad de **50**.

## Restricciones

### 1. Tiempo de producción
- Cada silla requiere **2 horas** de trabajo.
- Cada mesa requiere **5 horas** de trabajo.
- La fábrica dispone de un máximo de **100 horas** por día.

### 2. Materiales
- Cada silla requiere **1 unidad de madera**.
- Cada mesa requiere **3 unidades de madera**.
- La fábrica dispone de un máximo de **60 unidades de madera** por día.

### 3. Demanda
- La demanda diaria máxima es de **20 sillas**.
- La demanda diaria máxima es de **10 mesas**.
"""

# ============================================================
# EJERCICIO DE PROGRAMACIÓN LINEAL
# Fábrica de sillas y mesas
# Ejercicio #1 - facil
# ============================================================

from pulp import LpMaximize, LpProblem, LpVariable, LpStatus, value

# ============================================================
# 1) VARIABLES DE DECISIÓN
# ============================================================
print("2. VARIABLES DE DECISIÓN")
print("X1 = número de sillas que debe producir la fábrica diariamente")
print("X2 = número de mesas que debe producir la fábrica diariamente")
print()

X1 = LpVariable("X1_Sillas", lowBound=0, cat="Integer")
X2 = LpVariable("X2_Mesas", lowBound=0, cat="Integer")

# ============================================================
# 2) FUNCIÓN OBJETIVO
# ============================================================
print("3. FUNCIÓN OBJETIVO")
print("Max Z = 30X1 + 50X2")
print()

modelo = LpProblem("Maximizacion_Utilidad", LpMaximize)
modelo += 30 * X1 + 50 * X2, "Funcion_Objetivo"

# ============================================================
# 3) RESTRICCIONES
# ============================================================
print("4. RESTRICCIONES")
print("2X1 + 5X2 <= 100   -> Restricción de tiempo")
print("X1 + 3X2 <= 60     -> Restricción de material")
print("X1 <= 20           -> Demanda máxima de sillas")
print("X2 <= 10           -> Demanda máxima de mesas")
print("X1, X2 >= 0")
print()

modelo += 2 * X1 + 5 * X2 <= 100, "Restriccion_Tiempo"
modelo += 1 * X1 + 3 * X2 <= 60, "Restriccion_Material"
modelo += X1 <= 20, "Demanda_Sillas"
modelo += X2 <= 10, "Demanda_Mesas"

# ============================================================
# 4) SOLUCIÓN
# ============================================================
print("5. SOLUCIÓN DEL MODELO")
modelo.solve()

print("Estado de la solución:", LpStatus[modelo.status])
print()

print("Valores óptimos encontrados:")
print("X1 (Sillas) =", int(X1.varValue))
print("X2 (Mesas)  =", int(X2.varValue))
print()

print("Utilidad máxima:")
print("Z =", int(value(modelo.objective)))
print("\n" + "="*60 + "\n")

# ============================================================
# 5) VERIFICACIÓN DE RESTRICCIONES
# ============================================================
x1 = int(X1.varValue)
x2 = int(X2.varValue)

print("6. VERIFICACIÓN DE RESTRICCIONES")
print(f"Tiempo usado: 2({x1}) + 5({x2}) = {2*x1 + 5*x2} <= 100")
print(f"Material usado: 1({x1}) + 3({x2}) = {x1 + 3*x2} <= 60")
print(f"Demanda sillas: {x1} <= 20")
print(f"Demanda mesas: {x2} <= 10")
print()

# ============================================================
# 6) RESPUESTA FINAL
# ============================================================
print("7. RESPUESTA FINAL")
print(f"La fábrica debe producir {x1} sillas y {x2} mesas por día.")
print(f"La utilidad máxima que obtiene es de {int(value(modelo.objective))}.")

"""# Problema de Asignación de Aplicaciones en Servidores

Un centro de datos tiene tres servidores (**S1, S2, S3**) que deben ejecutar cuatro aplicaciones (**A1, A2, A3, A4**).

Cada servidor tiene una **capacidad de procesamiento limitada (en GHz)** y un **consumo de energía diferente**.  
Cada aplicación requiere un mínimo de capacidad de procesamiento para funcionar correctamente.

## Objetivo

Asignar las aplicaciones a los servidores de manera que se **minimice el consumo total de energía**, sin exceder la capacidad de los servidores.

## Datos

### 1. Capacidad de los servidores (en GHz)
- **S1:** 100 GHz  
- **S2:** 150 GHz  
- **S3:** 200 GHz  

### 2. Consumo de energía por GHz
- **S1:** 0.5 W/GHz  
- **S2:** 0.4 W/GHz  
- **S3:** 0.3 W/GHz  

### 3. Requerimientos de las aplicaciones (en GHz)
- **A1:** 50 GHz  
- **A2:** 60 GHz  
- **A3:** 80 GHz  
- **A4:** 70 GHz  
"""

# ============================================================
# EJERCICIO, VARIABLES, FUNCIÓN OBJETIVO, RESTRICCIONES, SOLUCIÓN
# PROGRAMACIÓN LINEAL - CENTRO DE DATOS
# Ejercicio #2 - facil
# ============================================================

from pulp import LpMinimize, LpProblem, LpVariable, LpStatus, value

# ============================================================
# 2) VARIABLES DE DECISIÓN
# ============================================================
print("2) VARIABLES DE DECISIÓN")
print("x11 = GHz del servidor S1 asignados a la aplicación A1")
print("x12 = GHz del servidor S1 asignados a la aplicación A2")
print("x13 = GHz del servidor S1 asignados a la aplicación A3")
print("x14 = GHz del servidor S1 asignados a la aplicación A4")
print()
print("x21 = GHz del servidor S2 asignados a la aplicación A1")
print("x22 = GHz del servidor S2 asignados a la aplicación A2")
print("x23 = GHz del servidor S2 asignados a la aplicación A3")
print("x24 = GHz del servidor S2 asignados a la aplicación A4")
print()
print("x31 = GHz del servidor S3 asignados a la aplicación A1")
print("x32 = GHz del servidor S3 asignados a la aplicación A2")
print("x33 = GHz del servidor S3 asignados a la aplicación A3")
print("x34 = GHz del servidor S3 asignados a la aplicación A4")
print()

# Variables
x11 = LpVariable("x11", lowBound=0)
x12 = LpVariable("x12", lowBound=0)
x13 = LpVariable("x13", lowBound=0)
x14 = LpVariable("x14", lowBound=0)

x21 = LpVariable("x21", lowBound=0)
x22 = LpVariable("x22", lowBound=0)
x23 = LpVariable("x23", lowBound=0)
x24 = LpVariable("x24", lowBound=0)

x31 = LpVariable("x31", lowBound=0)
x32 = LpVariable("x32", lowBound=0)
x33 = LpVariable("x33", lowBound=0)
x34 = LpVariable("x34", lowBound=0)

# ============================================================
# 3) FUNCIÓN OBJETIVO
# ============================================================
print("3) FUNCIÓN OBJETIVO")
print("Min Z = 0.5x11 + 0.5x12 + 0.5x13 + 0.5x14")
print("      + 0.4x21 + 0.4x22 + 0.4x23 + 0.4x24")
print("      + 0.3x31 + 0.3x32 + 0.3x33 + 0.3x34")
print()

modelo = LpProblem("Centro_de_Datos", LpMinimize)

modelo += (
    0.5*x11 + 0.5*x12 + 0.5*x13 + 0.5*x14 +
    0.4*x21 + 0.4*x22 + 0.4*x23 + 0.4*x24 +
    0.3*x31 + 0.3*x32 + 0.3*x33 + 0.3*x34
), "Consumo_Total_Energia"

# ============================================================
# 4) RESTRICCIONES
# ============================================================
print("4) RESTRICCIONES")
print("Capacidad de los servidores:")
print("x11 + x12 + x13 + x14 <= 100")
print("x21 + x22 + x23 + x24 <= 150")
print("x31 + x32 + x33 + x34 <= 200")
print()
print("Requerimiento de las aplicaciones:")
print("x11 + x21 + x31 = 50")
print("x12 + x22 + x32 = 60")
print("x13 + x23 + x33 = 80")
print("x14 + x24 + x34 = 70")
print()
print("No negatividad:")
print("xij >= 0")
print()

# Restricciones de capacidad
modelo += x11 + x12 + x13 + x14 <= 100, "Capacidad_S1"
modelo += x21 + x22 + x23 + x24 <= 150, "Capacidad_S2"
modelo += x31 + x32 + x33 + x34 <= 200, "Capacidad_S3"

# Restricciones de requerimiento
modelo += x11 + x21 + x31 == 50, "Aplicacion_A1"
modelo += x12 + x22 + x32 == 60, "Aplicacion_A2"
modelo += x13 + x23 + x33 == 80, "Aplicacion_A3"
modelo += x14 + x24 + x34 == 70, "Aplicacion_A4"

# ============================================================
# 5) SOLUCIÓN
# ============================================================
print("5) SOLUCIÓN")
modelo.solve()

print("Estado de la solución:", LpStatus[modelo.status])
print()

print("Valores óptimos de las variables:")
print(f"x11 = {x11.varValue}")
print(f"x12 = {x12.varValue}")
print(f"x13 = {x13.varValue}")
print(f"x14 = {x14.varValue}")
print()

print(f"x21 = {x21.varValue}")
print(f"x22 = {x22.varValue}")
print(f"x23 = {x23.varValue}")
print(f"x24 = {x24.varValue}")
print()

print(f"x31 = {x31.varValue}")
print(f"x32 = {x32.varValue}")
print(f"x33 = {x33.varValue}")
print(f"x34 = {x34.varValue}")
print()

print("Consumo mínimo total de energía:")
print(f"Z = {value(modelo.objective)} W")
print()

print("Uso total de cada servidor:")
print(f"S1 = {value(x11 + x12 + x13 + x14)} GHz de 100 GHz")
print(f"S2 = {value(x21 + x22 + x23 + x24)} GHz de 150 GHz")
print(f"S3 = {value(x31 + x32 + x33 + x34)} GHz de 200 GHz")
print()

print("Procesamiento total asignado a cada aplicación:")
print(f"A1 = {value(x11 + x21 + x31)} GHz")
print(f"A2 = {value(x12 + x22 + x32)} GHz")
print(f"A3 = {value(x13 + x23 + x33)} GHz")
print(f"A4 = {value(x14 + x24 + x34)} GHz")
print()

print("Interpretación de la solución:")
print("La solución óptima asigna primero la mayor cantidad posible al servidor S3")
print("porque tiene el menor consumo por GHz, luego al servidor S2 y por último a S1 si es necesario.")

"""Una empresa debe abastecer a tres clientes (Cliente 1, Cliente 2 y Cliente 3) utilizando dos posibles bodegas (A y B). Cada cliente tiene una demanda semanal que debe ser satisfecha completamente: el Cliente 1 requiere 80 unidades, el Cliente 2 requiere 70 unidades y el Cliente 3 requiere 60 unidades.
Las bodegas tienen una capacidad máxima de envío semanal. La Bodega A puede enviar hasta 150 unidades y la Bodega B hasta 120 unidades. Además, abrir una bodega genera un costo fijo: abrir la Bodega A cuesta 500 y abrir la Bodega B cuesta 400.
Existen costos de transporte por unidad desde cada bodega hacia cada cliente. Desde la Bodega A, el costo por unidad es de 4 hacia el Cliente 1, 6 hacia el Cliente 2 y 9 hacia el Cliente 3. Desde la Bodega B, el costo por unidad es de 5 hacia el Cliente 1, 4 hacia el Cliente 2 y 7 hacia el Cliente 3.
La empresa debe decidir qué bodegas abrir y cuántas unidades enviar desde cada bodega a cada cliente, de tal manera que se satisfaga completamente la demanda de los clientes y no se exceda la capacidad de las bodegas.
Formular el modelo que permita determinar la cantidad a enviar desde cada bodega a cada cliente y la apertura de las bodegas, con el fin de minimizar los costos totales, considerando los costos fijos de apertura y los costos de transporte.
"""

# ============================================================
# EJERCICIO, VARIABLES, FUNCIÓN OBJETIVO, RESTRICCIONES, SOLUCIÓN
# PROGRAMACIÓN LINEAL ENTERA MIXTA (MLP)
# Problema de apertura de bodegas y transporte
# Ejercicio #3 - mediano
# ============================================================
from pulp import LpMinimize, LpProblem, LpVariable, LpStatus, value, LpBinary

# ============================================================
# 2) VARIABLES DE DECISIÓN
# ============================================================
print("2) VARIABLES DE DECISIÓN")
print("xij = unidades enviadas desde la bodega i al cliente j")
print("yA = 1 si se abre la Bodega A, 0 en caso contrario")
print("yB = 1 si se abre la Bodega B, 0 en caso contrario")
print()
print("xA1 = unidades enviadas desde A al Cliente 1")
print("xA2 = unidades enviadas desde A al Cliente 2")
print("xA3 = unidades enviadas desde A al Cliente 3")
print("xB1 = unidades enviadas desde B al Cliente 1")
print("xB2 = unidades enviadas desde B al Cliente 2")
print("xB3 = unidades enviadas desde B al Cliente 3")
print()

# Variables continuas de envío
xA1 = LpVariable("xA1", lowBound=0)
xA2 = LpVariable("xA2", lowBound=0)
xA3 = LpVariable("xA3", lowBound=0)

xB1 = LpVariable("xB1", lowBound=0)
xB2 = LpVariable("xB2", lowBound=0)
xB3 = LpVariable("xB3", lowBound=0)

# Variables binarias de apertura
yA = LpVariable("yA", cat=LpBinary)
yB = LpVariable("yB", cat=LpBinary)

# ============================================================
# 3) FUNCIÓN OBJETIVO
# ============================================================
print("3) FUNCIÓN OBJETIVO")
print("Min Z = 500yA + 400yB + 4xA1 + 6xA2 + 9xA3 + 5xB1 + 4xB2 + 7xB3")
print()

modelo = LpProblem("Apertura_Bodegas_y_Transporte", LpMinimize)

modelo += (
    500*yA + 400*yB +
    4*xA1 + 6*xA2 + 9*xA3 +
    5*xB1 + 4*xB2 + 7*xB3
), "Costo_Total"

# ============================================================
# 4) RESTRICCIONES
# ============================================================
print("4) RESTRICCIONES")
print("Demanda de los clientes:")
print("xA1 + xB1 = 80")
print("xA2 + xB2 = 70")
print("xA3 + xB3 = 60")
print()
print("Capacidad de las bodegas:")
print("xA1 + xA2 + xA3 <= 150yA")
print("xB1 + xB2 + xB3 <= 120yB")
print()
print("No negatividad:")
print("xij >= 0")
print()
print("Variables binarias:")
print("yA, yB = 0 o 1")
print()

# Restricciones de demanda
modelo += xA1 + xB1 == 80, "Demanda_Cliente_1"
modelo += xA2 + xB2 == 70, "Demanda_Cliente_2"
modelo += xA3 + xB3 == 60, "Demanda_Cliente_3"

# Restricciones de capacidad ligadas a apertura
modelo += xA1 + xA2 + xA3 <= 150 * yA, "Capacidad_Bodega_A"
modelo += xB1 + xB2 + xB3 <= 120 * yB, "Capacidad_Bodega_B"

# ============================================================
# 5) SOLUCIÓN
# ============================================================
print("5) SOLUCIÓN")
modelo.solve()

print("Estado de la solución:", LpStatus[modelo.status])
print()

print("Valores óptimos de las variables:")
print(f"xA1 = {xA1.varValue}")
print(f"xA2 = {xA2.varValue}")
print(f"xA3 = {xA3.varValue}")
print()
print(f"xB1 = {xB1.varValue}")
print(f"xB2 = {xB2.varValue}")
print(f"xB3 = {xB3.varValue}")
print()
print(f"yA = {yA.varValue}")
print(f"yB = {yB.varValue}")
print()

print("Costo mínimo total:")
print(f"Z = {value(modelo.objective)}")
print()

print("Uso total de cada bodega:")
print(f"Bodega A = {value(xA1 + xA2 + xA3)} unidades de 150")
print(f"Bodega B = {value(xB1 + xB2 + xB3)} unidades de 120")
print()

print("Demanda satisfecha de cada cliente:")
print(f"Cliente 1 = {value(xA1 + xB1)} unidades")
print(f"Cliente 2 = {value(xA2 + xB2)} unidades")
print(f"Cliente 3 = {value(xA3 + xB3)} unidades")
print()

print("Interpretación de la solución:")
if yA.varValue == 1:
    print("Se abre la Bodega A")
else:
    print("No se abre la Bodega A")

if yB.varValue == 1:
    print("Se abre la Bodega B")
else:
    print("No se abre la Bodega B")

print()
print(f"Enviar {xA1.varValue} unidades desde A al Cliente 1")
print(f"Enviar {xA2.varValue} unidades desde A al Cliente 2")
print(f"Enviar {xA3.varValue} unidades desde A al Cliente 3")
print(f"Enviar {xB1.varValue} unidades desde B al Cliente 1")
print(f"Enviar {xB2.varValue} unidades desde B al Cliente 2")
print(f"Enviar {xB3.varValue} unidades desde B al Cliente 3")

"""Una empresa manufacturera produce dos productos: A y B. Para ello puede operar hasta dos plantas, Planta 1 y Planta 2. Abrir una planta implica un costo fijo semanal de 600 para la Planta 1 y de 500 para la Planta 2.
La empresa cuenta con recursos limitados para la producción. Dispone de un máximo de 200 horas de mano de obra y 150 kg de materia prima por semana. Cada unidad del Producto A requiere 3 horas de mano de obra y 2 kg de materia prima, mientras que cada unidad del Producto B requiere 2 horas de mano de obra y 3 kg de materia prima.
Las plantas tienen una capacidad máxima de producción total. La Planta 1 puede producir hasta 80 unidades en total y la Planta 2 hasta 100 unidades en total. Cada planta puede producir ambos productos, pero únicamente si ha sido abierta.
La utilidad generada por cada unidad producida es de 30 para el Producto A y de 40 para el Producto B. Además, la empresa debe cumplir con una demanda mínima semanal de 40 unidades del Producto A y 30 unidades del Producto B.
La empresa debe decidir qué plantas abrir y cuántas unidades de cada producto producir en cada planta, con el fin de maximizar la ganancia total, considerando las utilidades obtenidas por la producción y los costos fijos de apertura de las plantas.
Formular el modelo que permita determinar la apertura de las plantas y la cantidad a producir de cada producto en cada una de ellas para maximizar la ganancia total, sujeto a las restricciones de mano de obra, materia prima, capacidad de producción y demanda mínima.
"""

# ============================================================
# EJERCICIO, VARIABLES, FUNCIÓN OBJETIVO, RESTRICCIONES, SOLUCIÓN
# PROGRAMACIÓN LINEAL ENTERA MIXTA (MLP)
# Producción con apertura de plantas
# Ejercicio #4 - mediano
# ============================================================

from pulp import LpMaximize, LpProblem, LpVariable, LpStatus, value, LpBinary

# ============================================================
# 2) VARIABLES DE DECISIÓN
# ============================================================
print("2) VARIABLES DE DECISIÓN")
print("xij = unidades del producto j producidas en la planta i")
print("y1 = 1 si se abre Planta 1")
print("y2 = 1 si se abre Planta 2")
print()

# Variables de producción
x1A = LpVariable("x1A", lowBound=0)
x1B = LpVariable("x1B", lowBound=0)

x2A = LpVariable("x2A", lowBound=0)
x2B = LpVariable("x2B", lowBound=0)

# Variables binarias
y1 = LpVariable("y1", cat=LpBinary)
y2 = LpVariable("y2", cat=LpBinary)

# ============================================================
# 3) FUNCIÓN OBJETIVO
# ============================================================
print("3) FUNCIÓN OBJETIVO")
print("Max Z = 30x1A + 40x1B + 30x2A + 40x2B - 600y1 - 500y2")
print()

modelo = LpProblem("Produccion_Plantas", LpMaximize)

modelo += (
    30*x1A + 40*x1B + 30*x2A + 40*x2B
    - 600*y1 - 500*y2
), "Ganancia_Total"

# ============================================================
# 4) RESTRICCIONES
# ============================================================
print("4) RESTRICCIONES")

print("Mano de obra:")
print("3x1A + 2x1B + 3x2A + 2x2B <= 200")
print()

print("Materia prima:")
print("2x1A + 3x1B + 2x2A + 3x2B <= 150")
print()

print("Capacidad por planta:")
print("x1A + x1B <= 80y1")
print("x2A + x2B <= 100y2")
print()

print("Demanda mínima:")
print("x1A + x2A >= 40")
print("x1B + x2B >= 30")
print()

print("No negatividad y binarias")
print("xij >= 0, yi = 0 o 1")
print()

# Mano de obra
modelo += 3*x1A + 2*x1B + 3*x2A + 2*x2B <= 200, "Mano_Obra"

# Materia prima
modelo += 2*x1A + 3*x1B + 2*x2A + 3*x2B <= 150, "Materia_Prima"

# Capacidad plantas
modelo += x1A + x1B <= 80 * y1, "Capacidad_P1"
modelo += x2A + x2B <= 100 * y2, "Capacidad_P2"

# Demanda mínima
modelo += x1A + x2A >= 40, "Demanda_A"
modelo += x1B + x2B >= 30, "Demanda_B"

# ============================================================
# 5) SOLUCIÓN
# ============================================================
print("5) SOLUCIÓN")
modelo.solve()

print("Estado:", LpStatus[modelo.status])
print()

print("Variables óptimas:")
print(f"x1A = {x1A.varValue}")
print(f"x1B = {x1B.varValue}")
print(f"x2A = {x2A.varValue}")
print(f"x2B = {x2B.varValue}")
print()
print(f"y1 (Planta 1) = {y1.varValue}")
print(f"y2 (Planta 2) = {y2.varValue}")
print()

print("Ganancia máxima:")
print(f"Z = {value(modelo.objective)}")
print()

print("Uso de recursos:")
print(f"Mano de obra usada = {value(3*x1A + 2*x1B + 3*x2A + 2*x2B)} de 200")
print(f"Materia prima usada = {value(2*x1A + 3*x1B + 2*x2A + 3*x2B)} de 150")
print()

print("Producción total:")
print(f"Producto A = {value(x1A + x2A)}")
print(f"Producto B = {value(x1B + x2B)}")
print()

print("Capacidad utilizada:")
print(f"Planta 1 = {value(x1A + x1B)} de 80")
print(f"Planta 2 = {value(x2A + x2B)} de 100")
print()

print("Interpretación:")
if y1.varValue == 1:
    print("Se abre Planta 1")
else:
    print("No se abre Planta 1")

if y2.varValue == 1:
    print("Se abre Planta 2")
else:
    print("No se abre Planta 2")

"""La red Anytown fue propuesta por primera vez por Walski y ha sido ampliamente utilizada como referencia en problemas de régimen de bombeo y expansión de redes. Esta red está conformada por 37 tuberías, 18 nodos, un tanque y un depósito. Además, es abastecida por una única estación de bombeo que cuenta con cuatro bombas idénticas.
El tanque tiene una elevación de 65,53 m y un diámetro de 12,2 m. El paso de tiempo hidráulico y el tiempo de los patrones de demanda son de una hora. Las demandas horarias son cíclicas y presentan tres intervalos crecientes a la 01:00, 11:00 y 21:00 horas, variando entre el 40% y el 120% de la demanda base. Las mayores demandas se presentan a las 09:00, 10:00, 11:00, 19:00 y 20:00 horas.
La tarifa de consumo de energía eléctrica varía en dos niveles, desde 0,0244 hasta 0,1194 dólares por kWh. El incremento en la tarifa inicia a las 08:00 horas y se mantiene hasta la medianoche. Dadas las condiciones físicas y de demanda de la red, esta debe garantizar un suministro mínimo de 15 mca en todos los nodos.
Adicionalmente, el nivel de agua en el tanque debe mantenerse dentro de los límites permitidos, con un mínimo de 67,67 m y un máximo de 76,2 m. Como la estación de bombeo cuenta con cuatro bombas de velocidad fija, durante cada hora del día existen 242^424 combinaciones posibles de operación.
Formular el modelo que permita determinar la combinación de bombas que debe operar en cada hora del día para minimizar el costo total de energía, cumpliendo con las restricciones de presión mínima en los nodos y de nivel permitido en el tanque.
"""

# ============================================================
# EJERCICIO, VARIABLES, FUNCIÓN OBJETIVO, RESTRICCIONES, SOLUCIÓN
# PROGRAMACIÓN POR RESTRICCIONES / COMBINATORIA
# Operación de bombas - Red Anytown (simplificado discretizado)
# Ejercicio #5 - avanzado
# ============================================================

from pulp import LpMinimize, LpProblem, LpVariable, LpStatus, value, LpBinary

# ============================================================
# 2) VARIABLES DE DECISIÓN
# ============================================================
print("2) VARIABLES DE DECISIÓN")
print("xhb = 1 si la bomba b opera en la hora h")
print("nh = nivel del tanque al final de la hora h")
print()

horas = range(24)
bombas = range(4)

# Variables binarias de operación de bombas
x = LpVariable.dicts("x", (horas, bombas), cat=LpBinary)

# Variables continuas de nivel del tanque
nivel = LpVariable.dicts("nivel", horas, lowBound=67.67, upBound=76.2)

# ============================================================
# PARÁMETROS SIMPLIFICADOS
# ============================================================

# Producción equivalente por bomba y por hora
produccion_bomba = 10

# Nivel inicial del tanque
nivel_inicial = 70

# Demanda horaria simplificada
demanda = [
    40, 40, 40, 40, 45, 50, 60, 70, 80, 90, 90, 85,
    70, 60, 55, 60, 65, 75, 85, 90, 90, 80, 60, 50
]

# Tarifas horarias
tarifa = []
for h in horas:
    if 8 <= h <= 23:
        tarifa.append(0.1194)
    else:
        tarifa.append(0.0244)

# ============================================================
# 3) FUNCIÓN OBJETIVO
# ============================================================
print("3) FUNCIÓN OBJETIVO")
print("Min Z =")
for h in horas:
    texto = f"{tarifa[h]}("
    for b in bombas:
        if b < 3:
            texto += f"x{h}{b+1} + "
        else:
            texto += f"x{h}{b+1}"
    texto += ")"
    if h < 23:
        texto += " +"
    print(texto)
print()

modelo = LpProblem("Operacion_Bombas_Anytown", LpMinimize)

modelo += sum(
    tarifa[h] * (x[h][0] + x[h][1] + x[h][2] + x[h][3])
    for h in horas
), "Costo_Total_Energia"

# ============================================================
# 4) RESTRICCIONES
# ============================================================
print("4) RESTRICCIONES")

print("Balance del tanque:")
print(f"nivel0 = {nivel_inicial} + {produccion_bomba}(x01 + x02 + x03 + x04) - {demanda[0]}")
for h in range(1, 24):
    print(f"nivel{h} = nivel{h-1} + {produccion_bomba}(x{h}1 + x{h}2 + x{h}3 + x{h}4) - {demanda[h]}")
print()

print("Presión mínima simplificada:")
for h in horas:
    print(f"{produccion_bomba}(x{h}1 + x{h}2 + x{h}3 + x{h}4) >= {0.4 * demanda[h]}")
print()

print("Máximo de bombas por hora:")
for h in horas:
    print(f"x{h}1 + x{h}2 + x{h}3 + x{h}4 <= 4")
print()

print("Límites del tanque:")
for h in horas:
    print(f"67.67 <= nivel{h} <= 76.2")
print()

print("Variables binarias:")
print("xhb = 0 o 1")
print()

# ------------------------------------------------------------
# Balance del tanque
# ------------------------------------------------------------
modelo += nivel[0] == nivel_inicial + produccion_bomba * (x[0][0] + x[0][1] + x[0][2] + x[0][3]) - demanda[0], "Balance_0"

for h in range(1, 24):
    modelo += nivel[h] == nivel[h-1] + produccion_bomba * (x[h][0] + x[h][1] + x[h][2] + x[h][3]) - demanda[h], f"Balance_{h}"

# ------------------------------------------------------------
# Presión mínima simplificada
# ------------------------------------------------------------
for h in horas:
    modelo += produccion_bomba * (x[h][0] + x[h][1] + x[h][2] + x[h][3]) >= 0.4 * demanda[h], f"Presion_{h}"

# ------------------------------------------------------------
# Máximo de bombas activas por hora
# ------------------------------------------------------------
for h in horas:
    modelo += x[h][0] + x[h][1] + x[h][2] + x[h][3] <= 4, f"Max_Bombas_{h}"

# ============================================================
# 5) SOLUCIÓN
# ============================================================
print("5) SOLUCIÓN")
modelo.solve()

print("Estado:", LpStatus[modelo.status])
print()

print("Costo mínimo total:")
print(f"Z = {value(modelo.objective)}")
print()

print("Operación de bombas por hora:")
for h in horas:
    print(f"Hora {h}:")
    print(f"x{h}1 = {x[h][0].varValue}")
    print(f"x{h}2 = {x[h][1].varValue}")
    print(f"x{h}3 = {x[h][2].varValue}")
    print(f"x{h}4 = {x[h][3].varValue}")
    print(f"Bombas encendidas = {value(x[h][0] + x[h][1] + x[h][2] + x[h][3])}")
    print()

print("Nivel del tanque por hora:")
for h in horas:
    print(f"nivel{h} = {nivel[h].varValue}")
print()

print("Verificación de presión mínima simplificada:")
for h in horas:
    produccion_h = value(produccion_bomba * (x[h][0] + x[h][1] + x[h][2] + x[h][3]))
    print(f"Hora {h}: {produccion_h} >= {0.4 * demanda[h]}")
print()

print("Interpretación:")
print("El modelo selecciona qué bombas activar en cada hora del día")
print("para minimizar el costo total de energía, respetando el balance")
print("del tanque, el nivel permitido y la presión mínima simplificada.")

"""Una empresa manufacturera produce dos productos, P1 y P2, los cuales deben ser distribuidos a dos bodegas, B1 y B2, durante tres períodos de tiempo t = 1, 2 y 3. En cada período, la empresa decide cuánto producir de cada producto y cómo distribuirlo a las bodegas para satisfacer la demanda. Los productos pueden almacenarse en las bodegas, generando costos de inventario, y además producir un producto en un período implica una decisión discreta de activación.

Los costos de producción son los siguientes: para el producto P1, el costo es 5 en el período 1, 6 en el período 2 y 5 en el período 3. Para el producto P2, el costo es 4 en el período 1, 5 en el período 2 y 6 en el período 3. Los costos de almacenamiento para ambos productos son de 1 por unidad en la bodega B1 y de 2 por unidad en la bodega B2 en todos los períodos. Los costos de transporte son, para el producto P1, 3 por unidad hacia la bodega B1 y 4 hacia la bodega B2 en todos los períodos; y para el producto P2, 2 por unidad hacia la bodega B1 y 3 hacia la bodega B2 en todos los períodos.

La demanda que debe satisfacerse es la siguiente: para el producto P1, en la bodega B1 es de 20, 15 y 10 unidades en los períodos 1, 2 y 3 respectivamente, y en la bodega B2 es de 10, 15 y 20 unidades en los mismos períodos. Para el producto P2, en la bodega B1 es de 10, 20 y 15 unidades en los períodos 1, 2 y 3 respectivamente, y en la bodega B2 es de 15, 10 y 15 unidades en los mismos períodos. La capacidad máxima de producción en cada período es de 100 unidades, y el inventario inicial en todas las bodegas para ambos productos es igual a cero.

El objetivo es determinar cuánto producir de cada producto en cada período, cuánto enviar a cada bodega y cuánto inventario mantener, así como decidir si se activa o no la producción de cada producto en cada período, de manera que se minimice el costo total compuesto por los costos de producción, almacenamiento y transporte, cumpliendo con la demanda en cada período, respetando la capacidad de producción y garantizando el balance de inventarios a lo largo del tiempo.
"""

# ============================================================
# EJERCICIO, VARIABLES, FUNCIÓN OBJETIVO, RESTRICCIONES, SOLUCIÓN
# PROGRAMACIÓN POR RESTRICCIONES / COMBINATORIA
# Planeación de producción, distribución e inventarios
# Ejercicio #6 - avanzado
# ============================================================
from pulp import LpMinimize, LpProblem, LpVariable, LpStatus, value, LpBinary

# ============================================================
# 2) VARIABLES DE DECISIÓN
# ============================================================
print("2) VARIABLES DE DECISIÓN")
print("xpt = cantidad producida del producto p en el período t")
print("epbt = cantidad enviada del producto p a la bodega b en el período t")
print("ipbt = inventario del producto p en la bodega b al final del período t")
print("ypt = 1 si se activa la producción del producto p en el período t")
print()

# Producción
x11 = LpVariable("x11_P1_t1", lowBound=0)
x12 = LpVariable("x12_P1_t2", lowBound=0)
x13 = LpVariable("x13_P1_t3", lowBound=0)

x21 = LpVariable("x21_P2_t1", lowBound=0)
x22 = LpVariable("x22_P2_t2", lowBound=0)
x23 = LpVariable("x23_P2_t3", lowBound=0)

# Envíos P1
e111 = LpVariable("e111_P1_B1_t1", lowBound=0)
e112 = LpVariable("e112_P1_B1_t2", lowBound=0)
e113 = LpVariable("e113_P1_B1_t3", lowBound=0)

e121 = LpVariable("e121_P1_B2_t1", lowBound=0)
e122 = LpVariable("e122_P1_B2_t2", lowBound=0)
e123 = LpVariable("e123_P1_B2_t3", lowBound=0)

# Envíos P2
e211 = LpVariable("e211_P2_B1_t1", lowBound=0)
e212 = LpVariable("e212_P2_B1_t2", lowBound=0)
e213 = LpVariable("e213_P2_B1_t3", lowBound=0)

e221 = LpVariable("e221_P2_B2_t1", lowBound=0)
e222 = LpVariable("e222_P2_B2_t2", lowBound=0)
e223 = LpVariable("e223_P2_B2_t3", lowBound=0)

# Inventarios P1
i111 = LpVariable("i111_P1_B1_t1", lowBound=0)
i112 = LpVariable("i112_P1_B1_t2", lowBound=0)
i113 = LpVariable("i113_P1_B1_t3", lowBound=0)

i121 = LpVariable("i121_P1_B2_t1", lowBound=0)
i122 = LpVariable("i122_P1_B2_t2", lowBound=0)
i123 = LpVariable("i123_P1_B2_t3", lowBound=0)

# Inventarios P2
i211 = LpVariable("i211_P2_B1_t1", lowBound=0)
i212 = LpVariable("i212_P2_B1_t2", lowBound=0)
i213 = LpVariable("i213_P2_B1_t3", lowBound=0)

i221 = LpVariable("i221_P2_B2_t1", lowBound=0)
i222 = LpVariable("i222_P2_B2_t2", lowBound=0)
i223 = LpVariable("i223_P2_B2_t3", lowBound=0)

# Activación binaria
y11 = LpVariable("y11_P1_t1", cat=LpBinary)
y12 = LpVariable("y12_P1_t2", cat=LpBinary)
y13 = LpVariable("y13_P1_t3", cat=LpBinary)

y21 = LpVariable("y21_P2_t1", cat=LpBinary)
y22 = LpVariable("y22_P2_t2", cat=LpBinary)
y23 = LpVariable("y23_P2_t3", cat=LpBinary)

# ============================================================
# 3) FUNCIÓN OBJETIVO
# ============================================================
print("3) FUNCIÓN OBJETIVO")
print("Min Z = 5x11 + 6x12 + 5x13 + 4x21 + 5x22 + 6x23")
print("      + 3e111 + 3e112 + 3e113 + 4e121 + 4e122 + 4e123")
print("      + 2e211 + 2e212 + 2e213 + 3e221 + 3e222 + 3e223")
print("      + 1i111 + 1i112 + 1i113 + 2i121 + 2i122 + 2i123")
print("      + 1i211 + 1i212 + 1i213 + 2i221 + 2i222 + 2i223")
print()

modelo = LpProblem("Produccion_Distribucion_Inventario", LpMinimize)

modelo += (
    5*x11 + 6*x12 + 5*x13 +
    4*x21 + 5*x22 + 6*x23 +
    3*e111 + 3*e112 + 3*e113 +
    4*e121 + 4*e122 + 4*e123 +
    2*e211 + 2*e212 + 2*e213 +
    3*e221 + 3*e222 + 3*e223 +
    1*i111 + 1*i112 + 1*i113 +
    2*i121 + 2*i122 + 2*i123 +
    1*i211 + 1*i212 + 1*i213 +
    2*i221 + 2*i222 + 2*i223
), "Costo_Total"

# ============================================================
# 4) RESTRICCIONES
# ============================================================
print("4) RESTRICCIONES")

print("Capacidad de producción por período:")
print("x11 + x21 <= 100")
print("x12 + x22 <= 100")
print("x13 + x23 <= 100")
print()

print("Activación de producción:")
print("x11 <= 100y11")
print("x12 <= 100y12")
print("x13 <= 100y13")
print("x21 <= 100y21")
print("x22 <= 100y22")
print("x23 <= 100y23")
print()

print("Balance producción - envíos:")
print("x11 = e111 + e121")
print("x12 = e112 + e122")
print("x13 = e113 + e123")
print("x21 = e211 + e221")
print("x22 = e212 + e222")
print("x23 = e213 + e223")
print()

print("Balance de inventarios:")
print("e111 - 20 = i111")
print("i111 + e112 - 15 = i112")
print("i112 + e113 - 10 = i113")
print()
print("e121 - 10 = i121")
print("i121 + e122 - 15 = i122")
print("i122 + e123 - 20 = i123")
print()
print("e211 - 10 = i211")
print("i211 + e212 - 20 = i212")
print("i212 + e213 - 15 = i213")
print()
print("e221 - 15 = i221")
print("i221 + e222 - 10 = i222")
print("i222 + e223 - 15 = i223")
print()

print("No negatividad y binarias:")
print("xpt >= 0, epbt >= 0, ipbt >= 0, ypt = 0 o 1")
print()

M = 100

# Capacidad por período
modelo += x11 + x21 <= 100, "Capacidad_t1"
modelo += x12 + x22 <= 100, "Capacidad_t2"
modelo += x13 + x23 <= 100, "Capacidad_t3"

# Activación
modelo += x11 <= M * y11, "Activacion_P1_t1"
modelo += x12 <= M * y12, "Activacion_P1_t2"
modelo += x13 <= M * y13, "Activacion_P1_t3"

modelo += x21 <= M * y21, "Activacion_P2_t1"
modelo += x22 <= M * y22, "Activacion_P2_t2"
modelo += x23 <= M * y23, "Activacion_P2_t3"

# Balance producción - envíos
modelo += x11 == e111 + e121, "Balance_P1_t1"
modelo += x12 == e112 + e122, "Balance_P1_t2"
modelo += x13 == e113 + e123, "Balance_P1_t3"

modelo += x21 == e211 + e221, "Balance_P2_t1"
modelo += x22 == e212 + e222, "Balance_P2_t2"
modelo += x23 == e213 + e223, "Balance_P2_t3"

# Balance inventarios P1 B1
modelo += e111 - 20 == i111, "Inv_P1_B1_t1"
modelo += i111 + e112 - 15 == i112, "Inv_P1_B1_t2"
modelo += i112 + e113 - 10 == i113, "Inv_P1_B1_t3"

# Balance inventarios P1 B2
modelo += e121 - 10 == i121, "Inv_P1_B2_t1"
modelo += i121 + e122 - 15 == i122, "Inv_P1_B2_t2"
modelo += i122 + e123 - 20 == i123, "Inv_P1_B2_t3"

# Balance inventarios P2 B1
modelo += e211 - 10 == i211, "Inv_P2_B1_t1"
modelo += i211 + e212 - 20 == i212, "Inv_P2_B1_t2"
modelo += i212 + e213 - 15 == i213, "Inv_P2_B1_t3"

# Balance inventarios P2 B2
modelo += e221 - 15 == i221, "Inv_P2_B2_t1"
modelo += i221 + e222 - 10 == i222, "Inv_P2_B2_t2"
modelo += i222 + e223 - 15 == i223, "Inv_P2_B2_t3"

# ============================================================
# 5) SOLUCIÓN
# ============================================================
print("5) SOLUCIÓN")
modelo.solve()

print("Estado:", LpStatus[modelo.status])
print()

print("Producción óptima:")
print(f"x11 = {x11.varValue}")
print(f"x12 = {x12.varValue}")
print(f"x13 = {x13.varValue}")
print(f"x21 = {x21.varValue}")
print(f"x22 = {x22.varValue}")
print(f"x23 = {x23.varValue}")
print()

print("Envíos óptimos:")
print(f"e111 = {e111.varValue}")
print(f"e112 = {e112.varValue}")
print(f"e113 = {e113.varValue}")
print(f"e121 = {e121.varValue}")
print(f"e122 = {e122.varValue}")
print(f"e123 = {e123.varValue}")
print(f"e211 = {e211.varValue}")
print(f"e212 = {e212.varValue}")
print(f"e213 = {e213.varValue}")
print(f"e221 = {e221.varValue}")
print(f"e222 = {e222.varValue}")
print(f"e223 = {e223.varValue}")
print()

print("Inventarios óptimos:")
print(f"i111 = {i111.varValue}")
print(f"i112 = {i112.varValue}")
print(f"i113 = {i113.varValue}")
print(f"i121 = {i121.varValue}")
print(f"i122 = {i122.varValue}")
print(f"i123 = {i123.varValue}")
print(f"i211 = {i211.varValue}")
print(f"i212 = {i212.varValue}")
print(f"i213 = {i213.varValue}")
print(f"i221 = {i221.varValue}")
print(f"i222 = {i222.varValue}")
print(f"i223 = {i223.varValue}")
print()

print("Activación de producción:")
print(f"y11 = {y11.varValue}")
print(f"y12 = {y12.varValue}")
print(f"y13 = {y13.varValue}")
print(f"y21 = {y21.varValue}")
print(f"y22 = {y22.varValue}")
print(f"y23 = {y23.varValue}")
print()

print("Costo mínimo total:")
print(f"Z = {value(modelo.objective)}")
print()

print("Verificación de capacidad por período:")
print(f"t1 = {value(x11 + x21)} de 100")
print(f"t2 = {value(x12 + x22)} de 100")
print(f"t3 = {value(x13 + x23)} de 100")
print()

print("Demanda satisfecha por período:")
print(f"P1-B1: t1={value(e111)}, t2={value(i111 + e112)}, t3={value(i112 + e113)}")
print(f"P1-B2: t1={value(e121)}, t2={value(i121 + e122)}, t3={value(i122 + e123)}")
print(f"P2-B1: t1={value(e211)}, t2={value(i211 + e212)}, t3={value(i212 + e213)}")
print(f"P2-B2: t1={value(e221)}, t2={value(i221 + e222)}, t3={value(i222 + e223)}")


print()
print("Interpretación:")
print("El modelo determina la cantidad óptima a producir de cada producto en cada período,")
print("la cantidad que debe enviarse a cada bodega y el inventario que conviene mantener")
print("al final de cada período, con el fin de minimizar el costo total del sistema.")
print()
print("Además, las variables binarias de activación indican en qué períodos conviene")
print("habilitar la producción de cada producto. Si una variable ypt toma valor 1,")
print("significa que en ese período sí se produce el producto correspondiente;")
print("si toma valor 0, significa que no se activa su producción.")
print()
print("La solución obtenida cumple simultáneamente con:")
print("- La capacidad máxima de producción en cada período.")
print("- El balance entre producción y envíos.")
print("- El balance de inventarios en cada bodega.")
print("- La satisfacción de la demanda en todos los períodos.")
print()
print("En conclusión, el modelo encuentra un plan de producción, distribución")
print("e inventario que satisface todas las necesidades de las bodegas al menor")
print("costo posible, aprovechando cuándo producir, cuánto enviar y cuánto almacenar.")