# -*- coding: utf-8 -*-
"""Problemas solucionados - general

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqRbD_hC505lUV9yOQncu4T2TlxQZVkA
"""

#Install libraries
!pip install pulp -q

"""# Problema de Optimización: Producción de Muebles

Una fábrica produce dos tipos de muebles: **sillas** y **mesas**.

- Cada silla genera una utilidad de **30**.
- Cada mesa genera una utilidad de **50**.

## Restricciones

### 1. Tiempo de producción
- Cada silla requiere **2 horas** de trabajo.
- Cada mesa requiere **5 horas** de trabajo.
- La fábrica dispone de un máximo de **100 horas** por día.

### 2. Materiales
- Cada silla requiere **1 unidad de madera**.
- Cada mesa requiere **3 unidades de madera**.
- La fábrica dispone de un máximo de **60 unidades de madera** por día.

### 3. Demanda
- La demanda diaria máxima es de **20 sillas**.
- La demanda diaria máxima es de **10 mesas**.
"""

# ============================================================
# PROGRAMACIÓN LINEAL - CENTRO DE DATOS
# EJERCICIO #1 - facil
# ============================================================
from pulp import LpMaximize, LpProblem, LpVariable, LpStatus, value

# ============================================================
# DATOS DEL PROBLEMA
# ============================================================

productos = {
    "X1": {
        "nombre": "Sillas",
        "descripcion": "número de sillas que debe producir la fábrica diariamente",
        "utilidad": 30,
        "tiempo": 2,
        "material": 1,
        "demanda": 20
    },
    "X2": {
        "nombre": "Mesas",
        "descripcion": "número de mesas que debe producir la fábrica diariamente",
        "utilidad": 50,
        "tiempo": 5,
        "material": 3,
        "demanda": 10
    }
}

recursos = {
    "Tiempo": {
        "coeficiente": "tiempo",
        "disponible": 100
    },
    "Material": {
        "coeficiente": "material",
        "disponible": 60
    }
}

# ============================================================
# MODELO
# ============================================================

modelo = LpProblem("Maximizacion_Utilidad", LpMaximize)

variables = {
    codigo: LpVariable(codigo, lowBound=0, cat="Integer")
    for codigo in productos
}

modelo += sum(
    datos["utilidad"] * variables[codigo]
    for codigo, datos in productos.items()
)

for nombre_recurso, recurso in recursos.items():
    modelo += sum(
        productos[codigo][recurso["coeficiente"]] * variables[codigo]
        for codigo in productos
    ) <= recurso["disponible"]

for codigo, datos in productos.items():
    modelo += variables[codigo] <= datos["demanda"]

modelo.solve()

# ============================================================
# SALIDA FORMATEADA
# ============================================================

print("1. VARIABLES DE DECISIÓN")
for codigo, datos in productos.items():
    print(f"{codigo} = {datos['descripcion']}")
print()

print("2. FUNCIÓN OBJETIVO")
funcion_objetivo = " + ".join(
    f"{datos['utilidad']}{codigo}"
    for codigo, datos in productos.items()
)
print(f"Max Z = {funcion_objetivo}")
print()

print("3. RESTRICCIONES")

for nombre_recurso, recurso in recursos.items():
    expresion = " + ".join(
        f"{productos[codigo][recurso['coeficiente']]}{codigo}"
        for codigo in productos
    )
    print(
        f"{expresion} <= {recurso['disponible']}   "
        f"-> Restricción de {nombre_recurso.lower()}"
    )

for codigo, datos in productos.items():
    print(f"{codigo} <= {datos['demanda']}           -> Demanda máxima de {datos['nombre'].lower()}")

variables_no_negativas = ", ".join(productos.keys())
print(f"{variables_no_negativas} >= 0")
print()

print("4. SOLUCIÓN DEL MODELO")
print("Estado de la solución:", LpStatus[modelo.status])
print()

print("Valores óptimos encontrados:")
for codigo, datos in productos.items():
    print(f"{codigo} ({datos['nombre']}) = {int(variables[codigo].varValue)}")
print()

print("Utilidad máxima:")
print("Z =", int(value(modelo.objective)))
print("\n" + "=" * 60 + "\n")

print("5. VERIFICACIÓN DE RESTRICCIONES")

for nombre_recurso, recurso in recursos.items():
    partes = []
    total_usado = 0

    for codigo in productos:
        coeficiente = productos[codigo][recurso["coeficiente"]]
        cantidad = int(variables[codigo].varValue)
        total_usado += coeficiente * cantidad
        partes.append(f"{coeficiente}({cantidad})")

    expresion = " + ".join(partes)

    print(
        f"{nombre_recurso} usado: {expresion} = "
        f"{total_usado} <= {recurso['disponible']}"
    )

for codigo, datos in productos.items():
    cantidad = int(variables[codigo].varValue)
    print(f"Demanda {datos['nombre'].lower()}: {cantidad} <= {datos['demanda']}")

print()

print("7. RESPUESTA FINAL")
print(
    f"La fábrica debe producir {int(variables['X1'].varValue)} sillas "
    f"y {int(variables['X2'].varValue)} mesas por día."
)
print(f"La utilidad máxima que obtiene es de {int(value(modelo.objective))}.")

"""# Problema de Asignación de Aplicaciones en Servidores

Un centro de datos tiene tres servidores (**S1, S2, S3**) que deben ejecutar cuatro aplicaciones (**A1, A2, A3, A4**).

Cada servidor tiene una **capacidad de procesamiento limitada (en GHz)** y un **consumo de energía diferente**.  
Cada aplicación requiere un mínimo de capacidad de procesamiento para funcionar correctamente.

## Objetivo

Asignar las aplicaciones a los servidores de manera que se **minimice el consumo total de energía**, sin exceder la capacidad de los servidores.

## Datos

### 1. Capacidad de los servidores (en GHz)
- **S1:** 100 GHz  
- **S2:** 150 GHz  
- **S3:** 200 GHz  

### 2. Consumo de energía por GHz
- **S1:** 0.5 W/GHz  
- **S2:** 0.4 W/GHz  
- **S3:** 0.3 W/GHz  

### 3. Requerimientos de las aplicaciones (en GHz)
- **A1:** 50 GHz  
- **A2:** 60 GHz  
- **A3:** 80 GHz  
- **A4:** 70 GHz  
"""

# ============================================================
# PROGRAMACIÓN LINEAL - CENTRO DE DATOS
# EJERCICIO #2 - facil
# ============================================================
from pulp import LpMinimize, LpProblem, LpVariable, LpStatus, value

servidores = {
    "S1": {"capacidad": 100, "consumo": 0.5},
    "S2": {"capacidad": 150, "consumo": 0.4},
    "S3": {"capacidad": 200, "consumo": 0.3}
}

aplicaciones = {
    "A1": {"requerimiento": 50},
    "A2": {"requerimiento": 60},
    "A3": {"requerimiento": 80},
    "A4": {"requerimiento": 70}
}

modelo = LpProblem("Centro_de_Datos", LpMinimize)

# Variables de decisión xij
x = {}

for i, servidor in enumerate(servidores, start=1):
    for j, aplicacion in enumerate(aplicaciones, start=1):
        nombre_variable = f"x{i}{j}"
        x[servidor, aplicacion] = LpVariable(nombre_variable, lowBound=0)

# Función objetivo
modelo += sum(
    servidores[servidor]["consumo"] * x[servidor, aplicacion]
    for servidor in servidores
    for aplicacion in aplicaciones
), "Consumo_Total_Energia"

# Restricciones de capacidad de servidores
for servidor in servidores:
    modelo += sum(
        x[servidor, aplicacion]
        for aplicacion in aplicaciones
    ) <= servidores[servidor]["capacidad"], f"Capacidad_{servidor}"

# Restricciones de requerimiento de aplicaciones
for aplicacion in aplicaciones:
    modelo += sum(
        x[servidor, aplicacion]
        for servidor in servidores
    ) == aplicaciones[aplicacion]["requerimiento"], f"Requerimiento_{aplicacion}"

# Resolver modelo
modelo.solve()

# ============================================================
# 1) Datos
# ============================================================
print("Datos:")

print("Capacidad de los servidores:")
for servidor, datos in servidores.items():
    print(f"{servidor} = {datos['capacidad']} GHz")

print()

print("Consumo de energía por GHz:")
for servidor, datos in servidores.items():
    print(f"{servidor} = {datos['consumo']} W/GHz")

print()

print("Requerimientos de las aplicaciones:")
for aplicacion, datos in aplicaciones.items():
    print(f"{aplicacion} = {datos['requerimiento']} GHz")

print("\n" + "=" * 70 + "\n")

# ============================================================
# 2) VARIABLES DE DECISIÓN
# ============================================================
print("2) VARIABLES DE DECISIÓN")

for i, servidor in enumerate(servidores, start=1):
    for j, aplicacion in enumerate(aplicaciones, start=1):
        print(
            f"x{i}{j} = GHz del servidor {servidor} "
            f"asignados a la aplicación {aplicacion}"
        )
    print()

# ============================================================
# 3) FUNCIÓN OBJETIVO
# ============================================================
print("3) FUNCIÓN OBJETIVO")

lineas_objetivo = []

for i, servidor in enumerate(servidores, start=1):
    terminos = []

    for j, aplicacion in enumerate(aplicaciones, start=1):
        consumo = servidores[servidor]["consumo"]
        terminos.append(f"{consumo}x{i}{j}")

    lineas_objetivo.append(" + ".join(terminos))

print(f"Min Z = {lineas_objetivo[0]}")
for linea in lineas_objetivo[1:]:
    print(f"      + {linea}")

print()

# ============================================================
# 4) RESTRICCIONES
# ============================================================
print("4) RESTRICCIONES")

print("Capacidad de los servidores:")
for i, servidor in enumerate(servidores, start=1):
    expresion = " + ".join(
        f"x{i}{j}"
        for j, aplicacion in enumerate(aplicaciones, start=1)
    )
    capacidad = servidores[servidor]["capacidad"]
    print(f"{expresion} <= {capacidad}")

print()

print("Requerimiento de las aplicaciones:")
for j, aplicacion in enumerate(aplicaciones, start=1):
    expresion = " + ".join(
        f"x{i}{j}"
        for i, servidor in enumerate(servidores, start=1)
    )
    requerimiento = aplicaciones[aplicacion]["requerimiento"]
    print(f"{expresion} = {requerimiento}")

print()

print("No negatividad:")
print("xij >= 0")
print()

# ============================================================
# 5) SOLUCIÓN
# ============================================================
print("5) SOLUCIÓN")
print("Estado de la solución:", LpStatus[modelo.status])
print()

print("Valores óptimos de las variables:")

for i, servidor in enumerate(servidores, start=1):
    for j, aplicacion in enumerate(aplicaciones, start=1):
        print(f"x{i}{j} = {x[servidor, aplicacion].varValue}")
    print()

print("Consumo mínimo total de energía:")
print(f"Z = {value(modelo.objective)} W")
print()

print("Uso total de cada servidor:")

for servidor in servidores:
    uso = sum(
        x[servidor, aplicacion].varValue
        for aplicacion in aplicaciones
    )
    capacidad = servidores[servidor]["capacidad"]
    print(f"{servidor} = {uso} GHz de {capacidad} GHz")

print()

print("Procesamiento total asignado a cada aplicación:")

for aplicacion in aplicaciones:
    asignado = sum(
        x[servidor, aplicacion].varValue
        for servidor in servidores
    )
    print(f"{aplicacion} = {asignado} GHz")

print()

print("Interpretación de la solución:")
print("La solución óptima asigna primero la mayor cantidad posible al servidor S3")
print("porque tiene el menor consumo por GHz, luego al servidor S2 y por último a S1 si es necesario.")

"""Una empresa debe abastecer a tres clientes (Cliente 1, Cliente 2 y Cliente 3) utilizando dos posibles bodegas (A y B). Cada cliente tiene una demanda semanal que debe ser satisfecha completamente: el Cliente 1 requiere 80 unidades, el Cliente 2 requiere 70 unidades y el Cliente 3 requiere 60 unidades.
Las bodegas tienen una capacidad máxima de envío semanal. La Bodega A puede enviar hasta 150 unidades y la Bodega B hasta 120 unidades. Además, abrir una bodega genera un costo fijo: abrir la Bodega A cuesta 500 y abrir la Bodega B cuesta 400.
Existen costos de transporte por unidad desde cada bodega hacia cada cliente. Desde la Bodega A, el costo por unidad es de 4 hacia el Cliente 1, 6 hacia el Cliente 2 y 9 hacia el Cliente 3. Desde la Bodega B, el costo por unidad es de 5 hacia el Cliente 1, 4 hacia el Cliente 2 y 7 hacia el Cliente 3.
La empresa debe decidir qué bodegas abrir y cuántas unidades enviar desde cada bodega a cada cliente, de tal manera que se satisfaga completamente la demanda de los clientes y no se exceda la capacidad de las bodegas.
Formular el modelo que permita determinar la cantidad a enviar desde cada bodega a cada cliente y la apertura de las bodegas, con el fin de minimizar los costos totales, considerando los costos fijos de apertura y los costos de transporte.
"""

# ============================================================
# PROGRAMACIÓN LINEAL ENTERA MIXTA (MLP)
# Apertura de bodegas y transporte
# Ejercicio #3 - medio
# ============================================================
from pulp import LpMinimize, LpProblem, LpVariable, LpStatus, value, LpBinary

# ============================================================
# 1) DATOS DEL PROBLEMA
# ============================================================

bodegas = {
    "A": {
        "capacidad": 150,
        "costo_fijo": 500
    },
    "B": {
        "capacidad": 120,
        "costo_fijo": 400
    }
}

clientes = {
    "1": {"demanda": 80},
    "2": {"demanda": 70},
    "3": {"demanda": 60}
}

costos_transporte = {
    ("A", "1"): 4,
    ("A", "2"): 6,
    ("A", "3"): 9,
    ("B", "1"): 5,
    ("B", "2"): 4,
    ("B", "3"): 7
}

# ============================================================
# 2) CREACIÓN DEL MODELO
# ============================================================

modelo = LpProblem("Apertura_Bodegas_y_Transporte", LpMinimize)

# Variables de envío xij
x = {
    (bodega, cliente): LpVariable(f"x{bodega}{cliente}", lowBound=0)
    for bodega in bodegas
    for cliente in clientes
}

# Variables binarias de apertura yi
y = {
    bodega: LpVariable(f"y{bodega}", cat=LpBinary)
    for bodega in bodegas
}

# Función objetivo
modelo += (
    sum(bodegas[bodega]["costo_fijo"] * y[bodega] for bodega in bodegas)
    +
    sum(costos_transporte[bodega, cliente] * x[bodega, cliente]
        for bodega in bodegas
        for cliente in clientes)
), "Costo_Total"

# Restricciones de demanda
for cliente in clientes:
    modelo += sum(
        x[bodega, cliente]
        for bodega in bodegas
    ) == clientes[cliente]["demanda"], f"Demanda_Cliente_{cliente}"

# Restricciones de capacidad ligadas a apertura
for bodega in bodegas:
    modelo += sum(
        x[bodega, cliente]
        for cliente in clientes
    ) <= bodegas[bodega]["capacidad"] * y[bodega], f"Capacidad_Bodega_{bodega}"

# Resolver modelo
modelo.solve()

# ============================================================
# 3) SALIDA FORMATEADA
# ============================================================

print("1) VARIABLES DE DECISIÓN")
print("xij = unidades enviadas desde la bodega i al cliente j")

for bodega in bodegas:
    print(f"y{bodega} = 1 si se abre la Bodega {bodega}, 0 en caso contrario")

print()

for bodega in bodegas:
    for cliente in clientes:
        print(f"x{bodega}{cliente} = unidades enviadas desde {bodega} al Cliente {cliente}")

print()

# ============================================================
# 4) FUNCIÓN OBJETIVO
# ============================================================

print("2) FUNCIÓN OBJETIVO")

terminos_fijos = [
    f"{bodegas[bodega]['costo_fijo']}y{bodega}"
    for bodega in bodegas
]

terminos_variables = [
    f"{costos_transporte[bodega, cliente]}x{bodega}{cliente}"
    for bodega in bodegas
    for cliente in clientes
]

print("Min Z = " + " + ".join(terminos_fijos + terminos_variables))
print()

# ============================================================
# 5) RESTRICCIONES
# ============================================================

print("3) RESTRICCIONES")

print("Demanda de los clientes:")
for cliente in clientes:
    expresion = " + ".join(
        f"x{bodega}{cliente}"
        for bodega in bodegas
    )
    print(f"{expresion} = {clientes[cliente]['demanda']}")

print()

print("Capacidad de las bodegas:")
for bodega in bodegas:
    expresion = " + ".join(
        f"x{bodega}{cliente}"
        for cliente in clientes
    )
    print(f"{expresion} <= {bodegas[bodega]['capacidad']}y{bodega}")

print()

print("No negatividad:")
print("xij >= 0")
print()

print("Variables binarias:")
variables_binarias = ", ".join(f"y{bodega}" for bodega in bodegas)
print(f"{variables_binarias} = 0 o 1")
print()

# ============================================================
# 6) SOLUCIÓN
# ============================================================

print("4) SOLUCIÓN")
print("Estado de la solución:", LpStatus[modelo.status])
print()

print("Valores óptimos de las variables:")

for bodega in bodegas:
    for cliente in clientes:
        print(f"x{bodega}{cliente} = {x[bodega, cliente].varValue}")
    print()

for bodega in bodegas:
    print(f"y{bodega} = {y[bodega].varValue}")

print()

print("Costo mínimo total:")
print(f"Z = {value(modelo.objective)}")
print()

print("Uso total de cada bodega:")
for bodega in bodegas:
    uso = sum(
        x[bodega, cliente].varValue
        for cliente in clientes
    )
    capacidad = bodegas[bodega]["capacidad"]
    print(f"Bodega {bodega} = {uso} unidades de {capacidad}")

print()

print("Demanda satisfecha de cada cliente:")
for cliente in clientes:
    demanda_satisfecha = sum(
        x[bodega, cliente].varValue
        for bodega in bodegas
    )
    print(f"Cliente {cliente} = {demanda_satisfecha} unidades")

print()

print("Interpretación de la solución:")
for bodega in bodegas:
    if y[bodega].varValue == 1:
        print(f"Se abre la Bodega {bodega}")
    else:
        print(f"No se abre la Bodega {bodega}")

print()

for bodega in bodegas:
    for cliente in clientes:
        print(
            f"Enviar {x[bodega, cliente].varValue} unidades "
            f"desde {bodega} al Cliente {cliente}"
        )

"""Una empresa manufacturera produce dos productos: A y B. Para ello puede operar hasta dos plantas, Planta 1 y Planta 2. Abrir una planta implica un costo fijo semanal de 600 para la Planta 1 y de 500 para la Planta 2.
La empresa cuenta con recursos limitados para la producción. Dispone de un máximo de 200 horas de mano de obra y 150 kg de materia prima por semana. Cada unidad del Producto A requiere 3 horas de mano de obra y 2 kg de materia prima, mientras que cada unidad del Producto B requiere 2 horas de mano de obra y 3 kg de materia prima.
Las plantas tienen una capacidad máxima de producción total. La Planta 1 puede producir hasta 80 unidades en total y la Planta 2 hasta 100 unidades en total. Cada planta puede producir ambos productos, pero únicamente si ha sido abierta.
La utilidad generada por cada unidad producida es de 30 para el Producto A y de 40 para el Producto B. Además, la empresa debe cumplir con una demanda mínima semanal de 40 unidades del Producto A y 30 unidades del Producto B.
La empresa debe decidir qué plantas abrir y cuántas unidades de cada producto producir en cada planta, con el fin de maximizar la ganancia total, considerando las utilidades obtenidas por la producción y los costos fijos de apertura de las plantas.
Formular el modelo que permita determinar la apertura de las plantas y la cantidad a producir de cada producto en cada una de ellas para maximizar la ganancia total, sujeto a las restricciones de mano de obra, materia prima, capacidad de producción y demanda mínima.
"""

# ============================================================
# PROGRAMACIÓN LINEAL ENTERA MIXTA (MLP)
# Producción con apertura de plantas
# Ejercicio #4 - medio
# ============================================================
from pulp import LpMaximize, LpProblem, LpVariable, LpStatus, value, LpBinary

# ============================================================
# 1) DATOS DEL PROBLEMA
# ============================================================

plantas = {
    "1": {
        "nombre": "Planta 1",
        "capacidad": 80,
        "costo_fijo": 600
    },
    "2": {
        "nombre": "Planta 2",
        "capacidad": 100,
        "costo_fijo": 500
    }
}

productos = {
    "A": {
        "utilidad": 30,
        "demanda_minima": 40,
        "recursos": {
            "Mano de obra": 3,
            "Materia prima": 2
        }
    },
    "B": {
        "utilidad": 40,
        "demanda_minima": 30,
        "recursos": {
            "Mano de obra": 2,
            "Materia prima": 3
        }
    }
}

recursos = {
    "Mano de obra": {
        "unidad": "horas",
        "disponible": 200
    },
    "Materia prima": {
        "unidad": "kg",
        "disponible": 150
    }
}

# ============================================================
# 2) CREACIÓN DEL MODELO
# ============================================================

modelo = LpProblem("Produccion_Plantas", LpMaximize)

x = {
    (planta, producto): LpVariable(f"x{planta}{producto}", lowBound=0)
    for planta in plantas
    for producto in productos
}

y = {
    planta: LpVariable(f"y{planta}", cat=LpBinary)
    for planta in plantas
}

# Función objetivo
modelo += (
    sum(
        productos[producto]["utilidad"] * x[planta, producto]
        for planta in plantas
        for producto in productos
    )
    -
    sum(
        plantas[planta]["costo_fijo"] * y[planta]
        for planta in plantas
    )
), "Ganancia_Total"

# Restricciones de recursos
for recurso, datos_recurso in recursos.items():
    modelo += sum(
        productos[producto]["recursos"][recurso] * x[planta, producto]
        for planta in plantas
        for producto in productos
    ) <= datos_recurso["disponible"], f"Restriccion_{recurso.replace(' ', '_')}"

# Restricciones de capacidad por planta
for planta in plantas:
    modelo += sum(
        x[planta, producto]
        for producto in productos
    ) <= plantas[planta]["capacidad"] * y[planta], f"Capacidad_Planta_{planta}"

# Restricciones de demanda mínima
for producto in productos:
    modelo += sum(
        x[planta, producto]
        for planta in plantas
    ) >= productos[producto]["demanda_minima"], f"Demanda_Minima_{producto}"

# Resolver
modelo.solve()

# ============================================================
# 3) VARIABLES DE DECISIÓN
# ============================================================

print("1) VARIABLES DE DECISIÓN")
print("xij = unidades del producto j producidas en la planta i")

for planta in plantas:
    print(f"y{planta} = 1 si se abre Planta {planta}")

print()

# ============================================================
# 4) FUNCIÓN OBJETIVO
# ============================================================

print("2) FUNCIÓN OBJETIVO")

terminos_utilidad = [
    f"{productos[producto]['utilidad']}x{planta}{producto}"
    for planta in plantas
    for producto in productos
]

terminos_costos = [
    f"{plantas[planta]['costo_fijo']}y{planta}"
    for planta in plantas
]

print("Max Z = " + " + ".join(terminos_utilidad) + " - " + " - ".join(terminos_costos))
print()

# ============================================================
# 5) RESTRICCIONES
# ============================================================

print("3) RESTRICCIONES")

for recurso, datos_recurso in recursos.items():
    print(f"{recurso}:")
    expresion = " + ".join(
        f"{productos[producto]['recursos'][recurso]}x{planta}{producto}"
        for planta in plantas
        for producto in productos
    )
    print(f"{expresion} <= {datos_recurso['disponible']}")
    print()

print("Capacidad por planta:")
for planta, datos in plantas.items():
    expresion = " + ".join(
        f"x{planta}{producto}"
        for producto in productos
    )
    print(f"{expresion} <= {datos['capacidad']}y{planta}")

print()

print("Demanda mínima:")
for producto, datos in productos.items():
    expresion = " + ".join(
        f"x{planta}{producto}"
        for planta in plantas
    )
    print(f"{expresion} >= {datos['demanda_minima']}")

print()

print("No negatividad y binarias")
print("xij >= 0, yi = 0 o 1")
print()

# ============================================================
# 6) SOLUCIÓN
# ============================================================

print("4) SOLUCIÓN")
estado = LpStatus[modelo.status]
print("Estado:", estado)
print()

if estado == "Optimal":

    print("Variables óptimas:")
    for planta in plantas:
        for producto in productos:
            print(f"x{planta}{producto} = {x[planta, producto].varValue}")

    print()

    for planta, datos in plantas.items():
        print(f"y{planta} ({datos['nombre']}) = {y[planta].varValue}")

    print()

    print("Ganancia máxima:")
    print(f"Z = {value(modelo.objective)}")
    print()

    print("Uso de recursos:")
    for recurso, datos_recurso in recursos.items():
        uso = sum(
            productos[producto]["recursos"][recurso] * x[planta, producto].varValue
            for planta in plantas
            for producto in productos
        )
        print(f"{recurso} usada = {uso} de {datos_recurso['disponible']}")

    print()

    print("Producción total:")
    for producto in productos:
        produccion = sum(
            x[planta, producto].varValue
            for planta in plantas
        )
        print(f"Producto {producto} = {produccion}")

    print()

    print("Capacidad utilizada:")
    for planta, datos in plantas.items():
        uso = sum(
            x[planta, producto].varValue
            for producto in productos
        )
        print(f"{datos['nombre']} = {uso} de {datos['capacidad']}")

    print()

    print("Interpretación:")
    for planta, datos in plantas.items():
        if y[planta].varValue == 1:
            print(f"Se abre {datos['nombre']}")
        else:
            print(f"No se abre {datos['nombre']}")

else:
    print("El modelo no tiene una solución factible.")
    print("No se deben interpretar los valores de las variables como solución óptima.")
    print()
    print("Posible causa:")
    print("Con los recursos disponibles no se puede cumplir simultáneamente")
    print("la demanda mínima de A y B junto con las demás restricciones.")

"""La red Anytown fue propuesta por primera vez por Walski y ha sido ampliamente utilizada como referencia en problemas de régimen de bombeo y expansión de redes. Esta red está conformada por 37 tuberías, 18 nodos, un tanque y un depósito. Además, es abastecida por una única estación de bombeo que cuenta con cuatro bombas idénticas.
El tanque tiene una elevación de 65,53 m y un diámetro de 12,2 m. El paso de tiempo hidráulico y el tiempo de los patrones de demanda son de una hora. Las demandas horarias son cíclicas y presentan tres intervalos crecientes a la 01:00, 11:00 y 21:00 horas, variando entre el 40% y el 120% de la demanda base. Las mayores demandas se presentan a las 09:00, 10:00, 11:00, 19:00 y 20:00 horas.
La tarifa de consumo de energía eléctrica varía en dos niveles, desde 0,0244 hasta 0,1194 dólares por kWh. El incremento en la tarifa inicia a las 08:00 horas y se mantiene hasta la medianoche. Dadas las condiciones físicas y de demanda de la red, esta debe garantizar un suministro mínimo de 15 mca en todos los nodos.
Adicionalmente, el nivel de agua en el tanque debe mantenerse dentro de los límites permitidos, con un mínimo de 67,67 m y un máximo de 76,2 m. Como la estación de bombeo cuenta con cuatro bombas de velocidad fija, durante cada hora del día existen 242^424 combinaciones posibles de operación.
Formular el modelo que permita determinar la combinación de bombas que debe operar en cada hora del día para minimizar el costo total de energía, cumpliendo con las restricciones de presión mínima en los nodos y de nivel permitido en el tanque.
"""

# ============================================================
# EJERCICIO, VARIABLES, FUNCIÓN OBJETIVO, RESTRICCIONES, SOLUCIÓN
# PROGRAMACIÓN POR RESTRICCIONES / COMBINATORIA
# Operación de bombas - Red Anytown (simplificado discretizado)
# Ejercicio #5 - avanzado
# ============================================================
from pulp import LpMinimize, LpProblem, LpVariable, LpStatus, value, LpBinary

# ============================================================
# 2) VARIABLES DE DECISIÓN
# ============================================================
print("2) VARIABLES DE DECISIÓN")
print("xhb = 1 si la bomba b opera en la hora h")
print("nh = nivel del tanque al final de la hora h")
print()

horas = range(24)
bombas = range(4)

# Variables binarias de operación de bombas
x = LpVariable.dicts("x", (horas, bombas), cat=LpBinary)

# Variables continuas de nivel del tanque
nivel = LpVariable.dicts("nivel", horas, lowBound=67.67, upBound=76.2)

# ============================================================
# PARÁMETROS SIMPLIFICADOS
# ============================================================

# Producción equivalente por bomba y por hora
produccion_bomba = 10

# Nivel inicial del tanque
nivel_inicial = 70

# Demanda horaria simplificada
demanda = [
    40, 40, 40, 40, 45, 50, 60, 70, 80, 90, 90, 85,
    70, 60, 55, 60, 65, 75, 85, 90, 90, 80, 60, 50
]

# Tarifas horarias
tarifa = []
for h in horas:
    if 8 <= h <= 23:
        tarifa.append(0.1194)
    else:
        tarifa.append(0.0244)

# ============================================================
# 3) FUNCIÓN OBJETIVO
# ============================================================
print("3) FUNCIÓN OBJETIVO")
print("Min Z =")
for h in horas:
    texto = f"{tarifa[h]}("
    for b in bombas:
        if b < 3:
            texto += f"x{h}{b+1} + "
        else:
            texto += f"x{h}{b+1}"
    texto += ")"
    if h < 23:
        texto += " +"
    print(texto)
print()

modelo = LpProblem("Operacion_Bombas_Anytown", LpMinimize)

modelo += sum(
    tarifa[h] * (x[h][0] + x[h][1] + x[h][2] + x[h][3])
    for h in horas
), "Costo_Total_Energia"

# ============================================================
# 4) RESTRICCIONES
# ============================================================
print("4) RESTRICCIONES")

print("Balance del tanque:")
print(f"nivel0 = {nivel_inicial} + {produccion_bomba}(x01 + x02 + x03 + x04) - {demanda[0]}")
for h in range(1, 24):
    print(f"nivel{h} = nivel{h-1} + {produccion_bomba}(x{h}1 + x{h}2 + x{h}3 + x{h}4) - {demanda[h]}")
print()

print("Presión mínima simplificada:")
for h in horas:
    print(f"{produccion_bomba}(x{h}1 + x{h}2 + x{h}3 + x{h}4) >= {0.4 * demanda[h]}")
print()

print("Máximo de bombas por hora:")
for h in horas:
    print(f"x{h}1 + x{h}2 + x{h}3 + x{h}4 <= 4")
print()

print("Límites del tanque:")
for h in horas:
    print(f"67.67 <= nivel{h} <= 76.2")
print()

print("Variables binarias:")
print("xhb = 0 o 1")
print()

# ------------------------------------------------------------
# Balance del tanque
# ------------------------------------------------------------
modelo += nivel[0] == nivel_inicial + produccion_bomba * (x[0][0] + x[0][1] + x[0][2] + x[0][3]) - demanda[0], "Balance_0"

for h in range(1, 24):
    modelo += nivel[h] == nivel[h-1] + produccion_bomba * (x[h][0] + x[h][1] + x[h][2] + x[h][3]) - demanda[h], f"Balance_{h}"

# ------------------------------------------------------------
# Presión mínima simplificada
# ------------------------------------------------------------
for h in horas:
    modelo += produccion_bomba * (x[h][0] + x[h][1] + x[h][2] + x[h][3]) >= 0.4 * demanda[h], f"Presion_{h}"

# ------------------------------------------------------------
# Máximo de bombas activas por hora
# ------------------------------------------------------------
for h in horas:
    modelo += x[h][0] + x[h][1] + x[h][2] + x[h][3] <= 4, f"Max_Bombas_{h}"

# ============================================================
# 5) SOLUCIÓN
# ============================================================
print("5) SOLUCIÓN")
modelo.solve()

print("Estado:", LpStatus[modelo.status])
print()

print("Costo mínimo total:")
print(f"Z = {value(modelo.objective)}")
print()

print("Operación de bombas por hora:")
for h in horas:
    print(f"Hora {h}:")
    print(f"x{h}1 = {x[h][0].varValue}")
    print(f"x{h}2 = {x[h][1].varValue}")
    print(f"x{h}3 = {x[h][2].varValue}")
    print(f"x{h}4 = {x[h][3].varValue}")
    print(f"Bombas encendidas = {value(x[h][0] + x[h][1] + x[h][2] + x[h][3])}")
    print()

print("Nivel del tanque por hora:")
for h in horas:
    print(f"nivel{h} = {nivel[h].varValue}")
print()

print("Verificación de presión mínima simplificada:")
for h in horas:
    produccion_h = value(produccion_bomba * (x[h][0] + x[h][1] + x[h][2] + x[h][3]))
    print(f"Hora {h}: {produccion_h} >= {0.4 * demanda[h]}")
print()

print("Interpretación:")
print("El modelo selecciona qué bombas activar en cada hora del día")
print("para minimizar el costo total de energía, respetando el balance")
print("del tanque, el nivel permitido y la presión mínima simplificada.")

"""Una empresa manufacturera produce dos productos, P1 y P2, los cuales deben ser distribuidos a dos bodegas, B1 y B2, durante tres períodos de tiempo t = 1, 2 y 3. En cada período, la empresa decide cuánto producir de cada producto y cómo distribuirlo a las bodegas para satisfacer la demanda. Los productos pueden almacenarse en las bodegas, generando costos de inventario, y además producir un producto en un período implica una decisión discreta de activación.

Los costos de producción son los siguientes: para el producto P1, el costo es 5 en el período 1, 6 en el período 2 y 5 en el período 3. Para el producto P2, el costo es 4 en el período 1, 5 en el período 2 y 6 en el período 3. Los costos de almacenamiento para ambos productos son de 1 por unidad en la bodega B1 y de 2 por unidad en la bodega B2 en todos los períodos. Los costos de transporte son, para el producto P1, 3 por unidad hacia la bodega B1 y 4 hacia la bodega B2 en todos los períodos; y para el producto P2, 2 por unidad hacia la bodega B1 y 3 hacia la bodega B2 en todos los períodos.

La demanda que debe satisfacerse es la siguiente: para el producto P1, en la bodega B1 es de 20, 15 y 10 unidades en los períodos 1, 2 y 3 respectivamente, y en la bodega B2 es de 10, 15 y 20 unidades en los mismos períodos. Para el producto P2, en la bodega B1 es de 10, 20 y 15 unidades en los períodos 1, 2 y 3 respectivamente, y en la bodega B2 es de 15, 10 y 15 unidades en los mismos períodos. La capacidad máxima de producción en cada período es de 100 unidades, y el inventario inicial en todas las bodegas para ambos productos es igual a cero.

El objetivo es determinar cuánto producir de cada producto en cada período, cuánto enviar a cada bodega y cuánto inventario mantener, así como decidir si se activa o no la producción de cada producto en cada período, de manera que se minimice el costo total compuesto por los costos de producción, almacenamiento y transporte, cumpliendo con la demanda en cada período, respetando la capacidad de producción y garantizando el balance de inventarios a lo largo del tiempo.
"""

# ============================================================
# PROGRAMACIÓN LINEAL ENTERA MIXTA
# Planeación de producción, distribución e inventarios
# Ejercicio #6 - avanzado
# ============================================================
from pulp import LpMinimize, LpProblem, LpVariable, LpStatus, value, LpBinary

# ============================================================
# 1) DATOS DEL PROBLEMA
# ============================================================

productos = ["1", "2"]
bodegas = ["1", "2"]
periodos = ["1", "2", "3"]

capacidad_periodo = {
    "1": 100,
    "2": 100,
    "3": 100
}

M = 100

costo_produccion = {
    ("1", "1"): 5,
    ("1", "2"): 6,
    ("1", "3"): 5,
    ("2", "1"): 4,
    ("2", "2"): 5,
    ("2", "3"): 6
}

costo_envio = {
    ("1", "1"): 3,
    ("1", "2"): 4,
    ("2", "1"): 2,
    ("2", "2"): 3
}

costo_inventario = {
    ("1", "1"): 1,
    ("1", "2"): 2,
    ("2", "1"): 1,
    ("2", "2"): 2
}

demanda = {
    ("1", "1", "1"): 20,
    ("1", "1", "2"): 15,
    ("1", "1", "3"): 10,

    ("1", "2", "1"): 10,
    ("1", "2", "2"): 15,
    ("1", "2", "3"): 20,

    ("2", "1", "1"): 10,
    ("2", "1", "2"): 20,
    ("2", "1", "3"): 15,

    ("2", "2", "1"): 15,
    ("2", "2", "2"): 10,
    ("2", "2", "3"): 15
}

# ============================================================
# 2) CREACIÓN DEL MODELO
# ============================================================

modelo = LpProblem("Produccion_Distribucion_Inventario", LpMinimize)

x = {
    (p, t): LpVariable(f"x{p}{t}", lowBound=0)
    for p in productos
    for t in periodos
}

e = {
    (p, b, t): LpVariable(f"e{p}{b}{t}", lowBound=0)
    for p in productos
    for b in bodegas
    for t in periodos
}

i = {
    (p, b, t): LpVariable(f"i{p}{b}{t}", lowBound=0)
    for p in productos
    for b in bodegas
    for t in periodos
}

y = {
    (p, t): LpVariable(f"y{p}{t}", cat=LpBinary)
    for p in productos
    for t in periodos
}

# Función objetivo
modelo += (
    sum(costo_produccion[p, t] * x[p, t] for p in productos for t in periodos)
    +
    sum(costo_envio[p, b] * e[p, b, t] for p in productos for b in bodegas for t in periodos)
    +
    sum(costo_inventario[p, b] * i[p, b, t] for p in productos for b in bodegas for t in periodos)
), "Costo_Total"

# Capacidad de producción por período
for t in periodos:
    modelo += sum(x[p, t] for p in productos) <= capacidad_periodo[t], f"Capacidad_t{t}"

# Activación de producción
for p in productos:
    for t in periodos:
        modelo += x[p, t] <= M * y[p, t], f"Activacion_P{p}_t{t}"

# Balance producción - envíos
for p in productos:
    for t in periodos:
        modelo += x[p, t] == sum(e[p, b, t] for b in bodegas), f"Balance_Produccion_P{p}_t{t}"

# Balance de inventarios
for p in productos:
    for b in bodegas:
        for t in periodos:
            if t == "1":
                modelo += e[p, b, t] - demanda[p, b, t] == i[p, b, t], f"Inventario_P{p}_B{b}_t{t}"
            else:
                periodo_anterior = str(int(t) - 1)
                modelo += (
                    i[p, b, periodo_anterior] + e[p, b, t] - demanda[p, b, t]
                    == i[p, b, t]
                ), f"Inventario_P{p}_B{b}_t{t}"

# Resolver
modelo.solve()

# ============================================================
# 3) SALIDA FORMATEADA
# ============================================================

print("1) VARIABLES DE DECISIÓN")
print("xpt = cantidad producida del producto p en el período t")
print("epbt = cantidad enviada del producto p a la bodega b en el período t")
print("ipbt = inventario del producto p en la bodega b al final del período t")
print("ypt = 1 si se activa la producción del producto p en el período t")
print()

print("2) FUNCIÓN OBJETIVO")

terminos_x = [
    f"{costo_produccion[p, t]}x{p}{t}"
    for p in productos
    for t in periodos
]

terminos_e = [
    f"{costo_envio[p, b]}e{p}{b}{t}"
    for p in productos
    for b in bodegas
    for t in periodos
]

terminos_i = [
    f"{costo_inventario[p, b]}i{p}{b}{t}"
    for p in productos
    for b in bodegas
    for t in periodos
]

print("Min Z = " + " + ".join(terminos_x))
print("      + " + " + ".join(terminos_e[:6]))
print("      + " + " + ".join(terminos_e[6:]))
print("      + " + " + ".join(terminos_i[:6]))
print("      + " + " + ".join(terminos_i[6:]))
print()

print("3) RESTRICCIONES")

print("Capacidad de producción por período:")
for t in periodos:
    expresion = " + ".join(f"x{p}{t}" for p in productos)
    print(f"{expresion} <= {capacidad_periodo[t]}")
print()

print("Activación de producción:")
for p in productos:
    for t in periodos:
        print(f"x{p}{t} <= {M}y{p}{t}")
print()

print("Balance producción - envíos:")
for p in productos:
    for t in periodos:
        expresion = " + ".join(f"e{p}{b}{t}" for b in bodegas)
        print(f"x{p}{t} = {expresion}")
print()

print("Balance de inventarios:")
for p in productos:
    for b in bodegas:
        for t in periodos:
            d = demanda[p, b, t]

            if t == "1":
                print(f"e{p}{b}{t} - {d} = i{p}{b}{t}")
            else:
                periodo_anterior = str(int(t) - 1)
                print(f"i{p}{b}{periodo_anterior} + e{p}{b}{t} - {d} = i{p}{b}{t}")
        print()

print("No negatividad y binarias:")
print("xpt >= 0, epbt >= 0, ipbt >= 0, ypt = 0 o 1")
print()

print("4) SOLUCIÓN")
estado = LpStatus[modelo.status]
print("Estado:", estado)
print()

if estado == "Optimal":

    print("Producción óptima:")
    for p in productos:
        for t in periodos:
            print(f"x{p}{t} = {x[p, t].varValue}")
    print()

    print("Envíos óptimos:")
    for p in productos:
        for b in bodegas:
            for t in periodos:
                print(f"e{p}{b}{t} = {e[p, b, t].varValue}")
    print()

    print("Inventarios óptimos:")
    for p in productos:
        for b in bodegas:
            for t in periodos:
                print(f"i{p}{b}{t} = {i[p, b, t].varValue}")
    print()

    print("Activación de producción:")
    for p in productos:
        for t in periodos:
            print(f"y{p}{t} = {y[p, t].varValue}")
    print()

    print("Costo mínimo total:")
    print(f"Z = {value(modelo.objective)}")
    print()

    print("Verificación de capacidad por período:")
    for t in periodos:
        uso = sum(x[p, t].varValue for p in productos)
        print(f"t{t} = {uso} de {capacidad_periodo[t]}")
    print()

    print("Demanda satisfecha por período:")
    for p in productos:
        for b in bodegas:
            valores = []

            for t in periodos:
                if t == "1":
                    satisfecho = e[p, b, t].varValue
                else:
                    periodo_anterior = str(int(t) - 1)
                    satisfecho = i[p, b, periodo_anterior].varValue + e[p, b, t].varValue

                valores.append(f"t{t}={satisfecho}")

            print(f"P{p}-B{b}: " + ", ".join(valores))

    print()
    print("Interpretación:")
    print("El modelo determina la cantidad óptima a producir de cada producto en cada período,")
    print("la cantidad que debe enviarse a cada bodega y el inventario que conviene mantener")
    print("al final de cada período, con el fin de minimizar el costo total del sistema.")
    print()
    print("Además, las variables binarias de activación indican en qué períodos conviene")
    print("habilitar la producción de cada producto. Si una variable ypt toma valor 1,")
    print("significa que en ese período sí se produce el producto correspondiente;")
    print("si toma valor 0, significa que no se activa su producción.")
    print()
    print("La solución obtenida cumple simultáneamente con:")
    print("- La capacidad máxima de producción en cada período.")
    print("- El balance entre producción y envíos.")
    print("- El balance de inventarios en cada bodega.")
    print("- La satisfacción de la demanda en todos los períodos.")
    print()
    print("En conclusión, el modelo encuentra un plan de producción, distribución")
    print("e inventario que satisface todas las necesidades de las bodegas al menor")
    print("costo posible, aprovechando cuándo producir, cuánto enviar y cuánto almacenar.")

else:
    print("El modelo no tiene solución óptima.")
    print("Estado encontrado:", estado)